services:
    r-backups:
        container_name: r-backups
        build:
            context: .
        environment:
            DATABASE_HOST: bbel-postgres
            DATABASE_USER: bbel_postgres
            DATABASE_PASSWORD: bbel_4dm1n
            DATABASE_NAME: bbel_postgres
        volumes:
            - ./backups:/backups
            - .:/app
        depends_on:
            - bbel-postgres
        stdin_open: true
        tty: true
        networks:
            - shared-network
        restart: always

    bbel-postgres:
        container_name: bbel-postgres
        restart: always
        image: postgres:15
        environment:
            POSTGRES_USER: bbel_postgres
            POSTGRES_PASSWORD: bbel_4dm1n
            POSTGRES_DB: bbel_postgres
        ports:
            - "5435:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - shared-network

    bbel-pgadmin:
        container_name: bbel-pgadmin
        restart: always
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: bbel_4dm1n
        ports:
            - "7070:80"
        extra_hosts:
            - "pgadmin2.localhost:127.0.0.1"
        depends_on:
            - bbel-postgres
        networks:
            - shared-network
        volumes:
            - pgadmin_data:/var/lib/pgadmin
volumes:
    postgres_data:
    pgadmin_data:

networks:
    shared-network:
        external: true
